default_stages: [pre-commit]

repos:
  - repo: local
    hooks:

    # - id: dotnet-format
      # name: Format
      # entry: dotnet format --exclude-diagnostics --verify-no-changes --verbosity diagnostic
      # language: system
      # pass_filenames: false
      # always_run: true

    # - id: dotnet-test-coverage
      # name: Run dotnet tests with coverage
      # entry: powershell.exe -NoProfile -ExecutionPolicy Bypass -File coverage.ps1
      # stages: [pre-commit]
      # language: system
      # pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
    - id: commitizen
      stages: [commit-msg]

  # this should go last since it will fix line endings broken by other tools
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-added-large-files
      #- id: check-case-conflict
    - id: check-yaml
    - id: check-ast
    - id: check-merge-conflict
    - id: double-quote-string-fixer
    - id: trailing-whitespace
      exclude: .github
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
