codecov:
    notify:
        after_n_builds: 2
flags:
  gsagh:
    carryforward: false
  integration:
    carryforward: false
ignore:
  - "GsaGHTests"  # ignore folders and all its contents
  - "GsaGH/Components/GraveyardComp"  # ignore folders and all its contents
