codecov:
    notify:
        after_n_builds: 2
flags:
  gsagh:
    carryforward: false
  integration:
    carryforward: false
ignore:
  - "GsaGHTests"  # ignore project (as it is referenced by Integration test)
  - "GsaGH/Components/GraveyardComp"  # ignore old versions of components in
  - "GsaGH/UI"  # ignore UI about box
  - "GsaGH/Properties" # ignore icons etc
  - "**/*Goo.cs" # ignore all files ending with *Goo.cs (goo wrappers, no logic should be placed here)
  - "**/*Parameter.cs" # ignore all files ending with *Parameter.cs (scaffolding for params, no logic should be placed here)
  - "GsaGH/Helpers/Graphics/Colours.cs" # ignore colours library class
