/*
 --- Start of auto-generated text --- 
This part of the sidebar file has been auto-generated, do not change it manually! Edit the generator here: https://github.com/arup-group/GSA-Grasshopper/tree/main/DocsGeneration
*/
{
  type: 'category',
	label: 'GSA Grasshopper plugin',
  items: [
    {
      type: 'category',
      label: 'Parameters',
      link: {type: 'doc', id: 'references/gsagh/gsagh-parameters'},
      items: [
        'references/gsagh/gsagh-grid-line-parameter',
        'references/gsagh/gsagh-list-parameter',
        'references/gsagh/gsagh-model-parameter',
        'references/gsagh/gsagh-bool6-parameter',
        'references/gsagh/gsagh-material-parameter',
        'references/gsagh/gsagh-offset-parameter',
        'references/gsagh/gsagh-property-2d-modifier-parameter',
        'references/gsagh/gsagh-property-2d-parameter',
        'references/gsagh/gsagh-property-3d-parameter',
        'references/gsagh/gsagh-release-parameter',
        'references/gsagh/gsagh-restraint-parameter',
        'references/gsagh/gsagh-section-modifier-parameter',
        'references/gsagh/gsagh-section-parameter',
        'references/gsagh/gsagh-spring-property-parameter',
        'references/gsagh/gsagh-assembly-parameter',
        'references/gsagh/gsagh-effective-length-options-parameter',
        'references/gsagh/gsagh-element-1d-parameter',
        'references/gsagh/gsagh-element-2d-parameter',
        'references/gsagh/gsagh-element-3d-parameter',
        'references/gsagh/gsagh-member-1d-parameter',
        'references/gsagh/gsagh-member-2d-parameter',
        'references/gsagh/gsagh-member-3d-parameter',
        'references/gsagh/gsagh-node-parameter',
        'references/gsagh/gsagh-grid-plane-surface-parameter',
        'references/gsagh/gsagh-load-case-parameter',
        'references/gsagh/gsagh-load-parameter',
        'references/gsagh/gsagh-analysis-case-parameter',
        'references/gsagh/gsagh-analysis-task-parameter',
        'references/gsagh/gsagh-combination-case-parameter',
        'references/gsagh/gsagh-design-task-parameter',
        'references/gsagh/gsagh-modal-dynamic-parameter-parameter',
        'references/gsagh/gsagh-result-parameter',
        'references/gsagh/gsagh-unitnumber-parameter'
      ]
    },
    {
      type: 'category',
      label: 'Components',
      link: {type: 'doc', id: 'references/gsagh/gsagh-components'},
      items: [
        {
          type: 'category',
          label: 'Model',
          link: {type: 'doc', id: 'references/gsagh/gsagh-model-components-overview'},
          items: [
            'references/gsagh/gsagh-create-model-component',
            'references/gsagh/gsagh-gwa-command-component',
            'references/gsagh/gsagh-open-model-component',
            'references/gsagh/gsagh-save-gsa-model-component',
            'references/gsagh/gsagh-get-model-analysis-component',
            'references/gsagh/gsagh-get-model-geometry-component',
            'references/gsagh/gsagh-get-model-loads-component',
            'references/gsagh/gsagh-get-model-materials-component',
            'references/gsagh/gsagh-get-model-properties-component',
            'references/gsagh/gsagh-steel-section-pool-names-component',
            'references/gsagh/gsagh-create-list-component',
            'references/gsagh/gsagh-get-model-lists-component',
            'references/gsagh/gsagh-list-info-component',
            'references/gsagh/gsagh-create-grid-line-component',
            'references/gsagh/gsagh-get-model-grid-lines-component',
            'references/gsagh/gsagh-grid-line-info-component',
            'references/gsagh/gsagh-material-quantities-component',
            'references/gsagh/gsagh-property-quantities-component',
            'references/gsagh/gsagh-model-titles-component',
            'references/gsagh/gsagh-model-units-component',
          ]
        },
        {
          type: 'category',
          label: 'Properties',
          link: {type: 'doc', id: 'references/gsagh/gsagh-properties-components-overview'},
          items: [
            'references/gsagh/gsagh-create-custom-material-component',
            'references/gsagh/gsagh-create-material-component',
            'references/gsagh/gsagh-edit-material-component',
            'references/gsagh/gsagh-material-properties-component',
            'references/gsagh/gsagh-create-spring-property-component',
            'references/gsagh/gsagh-get-spring-property-component',
            'references/gsagh/gsagh-create-profile-component',
            'references/gsagh/gsagh-edit-profile-component',
            'references/gsagh/gsagh-profile-dimensions-component',
            'references/gsagh/gsagh-section-properties-component',
            'references/gsagh/gsagh-taper-profile-component',
            'references/gsagh/gsagh-create-section-component',
            'references/gsagh/gsagh-create-section-modifier-component',
            'references/gsagh/gsagh-edit-section-component',
            'references/gsagh/gsagh-get-section-modifier-component',
            'references/gsagh/gsagh-create-2d-property-component',
            'references/gsagh/gsagh-create-2d-property-modifier-component',
            'references/gsagh/gsagh-edit-2d-property-component',
            'references/gsagh/gsagh-get-2d-property-modifier-component',
            'references/gsagh/gsagh-create-3d-property-component',
            'references/gsagh/gsagh-edit-3d-property-component',
            'references/gsagh/gsagh-create-bool6-component',
            'references/gsagh/gsagh-create-offset-component',
            'references/gsagh/gsagh-edit-bool6-component',
            'references/gsagh/gsagh-edit-offset-component',
          ]
        },
        {
          type: 'category',
          label: 'Geometry',
          link: {type: 'doc', id: 'references/gsagh/gsagh-geometry-components-overview'},
          items: [
            'references/gsagh/gsagh-create-support-component',
            'references/gsagh/gsagh-edit-node-component',
            'references/gsagh/gsagh-create-1d-element-component',
            'references/gsagh/gsagh-create-2d-element-component',
            'references/gsagh/gsagh-edit-1d-element-component',
            'references/gsagh/gsagh-edit-2d-element-component',
            'references/gsagh/gsagh-edit-3d-element-component',
            'references/gsagh/gsagh-create-1d-member-component',
            'references/gsagh/gsagh-create-2d-member-component',
            'references/gsagh/gsagh-create-3d-member-component',
            'references/gsagh/gsagh-edit-1d-member-component',
            'references/gsagh/gsagh-edit-2d-member-component',
            'references/gsagh/gsagh-edit-3d-member-component',
            'references/gsagh/gsagh-create-2d-elements-from-brep-component',
            'references/gsagh/gsagh-create-elements-from-members-component',
            'references/gsagh/gsagh-expand-beam-to-shell-component',
            'references/gsagh/gsagh-create-assembly-component',
            'references/gsagh/gsagh-get-assembly-component',
            'references/gsagh/gsagh-create-effective-length-options-component',
            'references/gsagh/gsagh-create-member-end-restraint-component',
            'references/gsagh/gsagh-get-effective-length-options-component',
            'references/gsagh/gsagh-member-end-restraint-info-component',
            'references/gsagh/gsagh-local-axes-component',
            'references/gsagh/gsagh-section-alignment-component',
          ]
        },
        {
          type: 'category',
          label: 'Loads',
          link: {type: 'doc', id: 'references/gsagh/gsagh-loads-components-overview'},
          items: [
            'references/gsagh/gsagh-create-load-case-component',
            'references/gsagh/gsagh-load-case-info-component',
            'references/gsagh/gsagh-create-beam-load-component',
            'references/gsagh/gsagh-create-beam-thermal-load-component',
            'references/gsagh/gsagh-create-face-load-component',
            'references/gsagh/gsagh-create-face-thermal-load-component',
            'references/gsagh/gsagh-create-gravity-load-component',
            'references/gsagh/gsagh-create-node-load-component',
            'references/gsagh/gsagh-create-grid-area-load-component',
            'references/gsagh/gsagh-create-grid-line-load-component',
            'references/gsagh/gsagh-create-grid-plane-component',
            'references/gsagh/gsagh-create-grid-point-load-component',
            'references/gsagh/gsagh-create-grid-surface-component',
            'references/gsagh/gsagh-grid-plane-surface-properties-component',
            'references/gsagh/gsagh-load-properties-component',
          ]
        },
        {
          type: 'category',
          label: 'Analysis',
          link: {type: 'doc', id: 'references/gsagh/gsagh-analysis-components-overview'},
          items: [
            'references/gsagh/gsagh-analyse-model-component',
            'references/gsagh/gsagh-steel-design-component',
            'references/gsagh/gsagh-analysis-task-info-component',
            'references/gsagh/gsagh-create-analysis-task-component',
            'references/gsagh/gsagh-analysis-case-info-component',
            'references/gsagh/gsagh-create-analysis-case-component',
            'references/gsagh/gsagh-create-modal-dynamic-parameter-component',
            'references/gsagh/gsagh-combination-case-info-component',
            'references/gsagh/gsagh-create-combination-case-component',
            'references/gsagh/gsagh-create-steel-design-task-component',
            'references/gsagh/gsagh-create-steel-section-pool-component',
            'references/gsagh/gsagh-design-task-info-component',
          ]
        },
        {
          type: 'category',
          label: 'Results',
          link: {type: 'doc', id: 'references/gsagh/gsagh-results-components-overview'},
          items: [
            'references/gsagh/gsagh-get-result-component',
            'references/gsagh/gsagh-get-result-cases-component',
            'references/gsagh/gsagh-select-result-component',
            'references/gsagh/gsagh-footfall-results-component',
            'references/gsagh/gsagh-nodal-forces-and-moments-component',
            'references/gsagh/gsagh-node-displacements-component',
            'references/gsagh/gsagh-reaction-forces-component',
            'references/gsagh/gsagh-spring-reaction-forces-component',
            'references/gsagh/gsagh-member-1d-displacements-component',
            'references/gsagh/gsagh-member-1d-forces-and-moments-component',
            'references/gsagh/gsagh-beam-derived-stresses-component',
            'references/gsagh/gsagh-beam-displacements-component',
            'references/gsagh/gsagh-beam-forces-and-moments-component',
            'references/gsagh/gsagh-beam-strain-energy-density-component',
            'references/gsagh/gsagh-beam-stresses-component',
            'references/gsagh/gsagh-element-2d-displacements-component',
            'references/gsagh/gsagh-element-2d-forces-and-moments-component',
            'references/gsagh/gsagh-element-2d-stresses-component',
            'references/gsagh/gsagh-element-3d-displacements-component',
            'references/gsagh/gsagh-element-3d-stresses-component',
            'references/gsagh/gsagh-assembly-displacements-component',
            'references/gsagh/gsagh-assembly-drift-indices-component',
            'references/gsagh/gsagh-assembly-drifts-component',
            'references/gsagh/gsagh-assembly-forces-and-moments-component',
            'references/gsagh/gsagh-global-performance-results-component',
            'references/gsagh/gsagh-steel-design-effective-length-component',
            'references/gsagh/gsagh-steel-utilisations-component',
            'references/gsagh/gsagh-total-loads-and-reactions-component',
          ]
        },
        {
          type: 'category',
          label: 'Display',
          link: {type: 'doc', id: 'references/gsagh/gsagh-display-components-overview'},
          items: [
            'references/gsagh/gsagh-annotate-component',
            'references/gsagh/gsagh-annotate-detailed-component',
            'references/gsagh/gsagh-preview-3d-sections-component',
            'references/gsagh/gsagh-preview-deformed-3d-sections-component',
            'references/gsagh/gsagh-load-diagrams-component',
            'references/gsagh/gsagh-assembly-result-diagrams-component',
            'references/gsagh/gsagh-reaction-force-diagrams-component',
            'references/gsagh/gsagh-result-diagrams-component',
            'references/gsagh/gsagh-assembly-results-component',
            'references/gsagh/gsagh-contour-1d-results-component',
            'references/gsagh/gsagh-contour-2d-results-component',
            'references/gsagh/gsagh-contour-3d-results-component',
            'references/gsagh/gsagh-contour-node-results-component',
            'references/gsagh/gsagh-line-result-info-component',
            'references/gsagh/gsagh-mesh-result-info-component',
            'references/gsagh/gsagh-point-result-info-component',
          ]
        },
      ]
    }
  ]
}
/*
--- End of auto-generated text ---
*/
