name: MSBuild

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore GsaGH.sln

    - name: Build
      run: msbuild /m /p:Configuration=Release GsaGH.sln
      
    - name: Run Tests
      run: dotnet test .\UnitTestGhSA\bin\Release\net6.0\UnitTestGhSA.dll
